export const ACCOUNT_LOADING = "ACCOUNT_LOADING";
export const ACCOUNT_ERROR = "ACCOUNT_ERROR";
export const ACCOUT_DATA_SUCCESS = "ACCOUT_DATA_SUCCESS";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAIL = "POST_DATA_FAIL";
